name: Build Mod
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      # 云端直接生成wrapper，不需要本地有gradle/wrapper
      - name: Generate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=8.14.3

      # 国内镜像加速
      - name: Mirror config
        run: |
          mkdir -p ~/.gradle
          cat > ~/.gradle/init.gradle <<'EOF'
          allprojects {
              repositories {
                  maven { url 'https://maven.aliyun.com/repository/public' }
                  maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
                  mavenCentral()
              }
          }
          EOF

      - name: Run genSources
        run: ./gradlew genSources

      - name: Build Jar
        run: ./gradlew jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModJar
          path: build/libs/*.jar
