name: Build Mod
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 写入gradle国内镜像配置
        run: |
          mkdir -p ~/.gradle
          cat > ~/.gradle/init.gradle <<'EOF'
          allprojects {
              repositories {
                  maven { url 'https://maven.aliyun.com/repository/public' }
                  maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
                  maven { url 'https://maven.aliyun.com/repository/minecraft' }
                  maven { url 'https://maven.aliyun.com/repository/forge' }
                  mavenCentral()
              }
          }
          EOF

      - name: Run genSources
        run: ./gradlew genSources

      - name: Package Mod Jar
        run: ./gradlew jar

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModJar
          path: build/libs/*.jar
